### ISSUE TITLE
Attribute selector mangling

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/postcss-minify-selectors#2]
```css
[class*=" icon-"]+.label, [class^="icon-"]+.label {
    margin-left: 0.25rem;
}
```

After:

```css
[class*=" icon-"]+.label, [class^="icon-"+.label {
    margin-left: 0.25rem;
}
```

```css
.control-group-inline>input[type="radio"] {
    width: 30px;
}
```

After:

```css
.control-group-inline>input[type="radio" {
    width: 30px;
}
```
